// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/ctfrancia/maple/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTournamentUseCase creates a new instance of MockTournamentUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTournamentUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTournamentUseCase {
	mock := &MockTournamentUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTournamentUseCase is an autogenerated mock type for the TournamentUseCase type
type MockTournamentUseCase struct {
	mock.Mock
}

type MockTournamentUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTournamentUseCase) EXPECT() *MockTournamentUseCase_Expecter {
	return &MockTournamentUseCase_Expecter{mock: &_m.Mock}
}

// ProcessTournamentRequest provides a mock function for the type MockTournamentUseCase
func (_mock *MockTournamentUseCase) ProcessTournamentRequest() ([]domain.Tournament, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ProcessTournamentRequest")
	}

	var r0 []domain.Tournament
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]domain.Tournament, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []domain.Tournament); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Tournament)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTournamentUseCase_ProcessTournamentRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessTournamentRequest'
type MockTournamentUseCase_ProcessTournamentRequest_Call struct {
	*mock.Call
}

// ProcessTournamentRequest is a helper method to define mock.On call
func (_e *MockTournamentUseCase_Expecter) ProcessTournamentRequest() *MockTournamentUseCase_ProcessTournamentRequest_Call {
	return &MockTournamentUseCase_ProcessTournamentRequest_Call{Call: _e.mock.On("ProcessTournamentRequest")}
}

func (_c *MockTournamentUseCase_ProcessTournamentRequest_Call) Run(run func()) *MockTournamentUseCase_ProcessTournamentRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTournamentUseCase_ProcessTournamentRequest_Call) Return(tournaments []domain.Tournament, err error) *MockTournamentUseCase_ProcessTournamentRequest_Call {
	_c.Call.Return(tournaments, err)
	return _c
}

func (_c *MockTournamentUseCase_ProcessTournamentRequest_Call) RunAndReturn(run func() ([]domain.Tournament, error)) *MockTournamentUseCase_ProcessTournamentRequest_Call {
	_c.Call.Return(run)
	return _c
}
