// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTournamentHandler creates a new instance of MockTournamentHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTournamentHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTournamentHandler {
	mock := &MockTournamentHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTournamentHandler is an autogenerated mock type for the TournamentHandler type
type MockTournamentHandler struct {
	mock.Mock
}

type MockTournamentHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTournamentHandler) EXPECT() *MockTournamentHandler_Expecter {
	return &MockTournamentHandler_Expecter{mock: &_m.Mock}
}

// GetTournamentsBasic provides a mock function for the type MockTournamentHandler
func (_mock *MockTournamentHandler) GetTournamentsBasic(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockTournamentHandler_GetTournamentsBasic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTournamentsBasic'
type MockTournamentHandler_GetTournamentsBasic_Call struct {
	*mock.Call
}

// GetTournamentsBasic is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockTournamentHandler_Expecter) GetTournamentsBasic(w interface{}, r interface{}) *MockTournamentHandler_GetTournamentsBasic_Call {
	return &MockTournamentHandler_GetTournamentsBasic_Call{Call: _e.mock.On("GetTournamentsBasic", w, r)}
}

func (_c *MockTournamentHandler_GetTournamentsBasic_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockTournamentHandler_GetTournamentsBasic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTournamentHandler_GetTournamentsBasic_Call) Return() *MockTournamentHandler_GetTournamentsBasic_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTournamentHandler_GetTournamentsBasic_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockTournamentHandler_GetTournamentsBasic_Call {
	_c.Run(run)
	return _c
}
