# Build the Go Binary.
FROM golang:1.25 AS build_scraper
ENV CGO_ENABLED=0
ARG BUILD_REF

# Create the service directory and the copy the module files first and then
# download the dependencies. If this doesn't change, we won't need to do this
# again in future builds.
RUN mkdir /maple
COPY go.* /maple/
WORKDIR /maple
RUN go mod download

# Copy the source code into the container.
COPY . /maple

# Build the service binary.
WORKDIR /maple/api/services/scrape
RUN go build -ldflags "-X main.build=${BUILD_REF}" -o scraper

# Run the Go Binary in Alpine.
FROM alpine:3.22
ARG BUILD_DATE
ARG BUILD_REF
RUN addgroup -g 1000 -S scraper && \
    adduser -u 1000 -h /scraper -G scraper -S scraper
COPY --from=build_scraper --chown=scraper:scraper /maple/api/services/scrape/scraper /scraper/scraper

RUN chmod +x /scraper/scraper

WORKDIR /scraper
USER scraper
CMD ["./scraper"]

LABEL org.opencontainers.image.created="${BUILD_DATE}" \
    org.opencontainers.image.title="scraper-service" \
    org.opencontainers.image.authors="Christian Francia <christian.francia@hey.com>" \
    org.opencontainers.image.source="https://github.com/ctfrancia/maple" \
    org.opencontainers.image.revision="${BUILD_REF}" \
    org.opencontainers.image.vendor=""
