global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'maple-backend'
    static_configs:
      - targets: ['backend:3010']  # Adjust port to where your app exposes /metrics
    
  - job_name: 'maple-metrics'
    static_configs:
      - targets: ['metrics:4020']
